'use client'

import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import Link from 'next/link'

import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import JourneySection from '@/components/how-it-works/JourneySection'
import SchoolJourney from '@/components/how-it-works/SchoolJourney'

// Student mockups
import SignupMockup from '@/components/how-it-works/mockups/SignupMockup'
import JoinClassMockup from '@/components/how-it-works/mockups/JoinClassMockup'
import ExamMockup from '@/components/how-it-works/mockups/ExamMockup'
import FeedbackMockup from '@/components/how-it-works/mockups/FeedbackMockup'
import AceProgressMockup from '@/components/how-it-works/mockups/AceProgressMockup'

// Teacher mockups
import CreateClassMockup from '@/components/how-it-works/mockups/CreateClassMockup'
import LibraryMockup from '@/components/how-it-works/mockups/LibraryMockup'
import SubmissionsMockup from '@/components/how-it-works/mockups/SubmissionsMockup'
import GradingMockup from '@/components/how-it-works/mockups/GradingMockup'
import GradebookMockup from '@/components/mockups/GradebookMockup'

const tabs = [
  { key: 'students' as const, label: 'For Students' },
  { key: 'teachers' as const, label: 'For Teachers' },
  { key: 'schools' as const, label: 'For Schools' },
]

type TabKey = (typeof tabs)[number]['key']

const studentSteps = [
  {
    title: 'Sign up free',
    description: 'Create your account in seconds. No credit card needed. Class students are always free.',
    mockup: <SignupMockup />,
  },
  {
    title: 'Join your class',
    description: 'Enter your class invite code from your teacher and you\'re in instantly.',
    mockup: <JoinClassMockup />,
  },
  {
    title: 'Take AI-generated exams',
    description: 'Your teacher assigns exams. Sit them anytime before the deadline — questions are GCSE-standard, generated by Claude AI.',
    mockup: <ExamMockup />,
  },
  {
    title: 'Get instant AI feedback',
    description: 'Submit and get examiner-level feedback within seconds. See your mark, what you got right, and exactly how to improve.',
    mockup: <FeedbackMockup />,
  },
  {
    title: 'Track your progress with Ace',
    description: 'Ace, your AI companion, tracks your weak topics and nudges you to practice. Watch your scores improve over time.',
    mockup: <AceProgressMockup />,
  },
]

const teacherSteps = [
  {
    title: 'Create your class',
    description: 'Set up a class in under a minute. Choose your qualification, board, and subject. Share the invite code with students.',
    mockup: <CreateClassMockup />,
  },
  {
    title: 'Assign from the library',
    description: 'Browse 300+ pre-built GCSE and IGCSE exams or generate custom ones with AI. Assign with a deadline in two clicks.',
    mockup: <LibraryMockup />,
  },
  {
    title: 'Students take exams',
    description: 'Students sit exams in their own time before the deadline. You get notified as submissions come in.',
    mockup: <SubmissionsMockup />,
  },
  {
    title: 'AI grades instantly',
    description: 'Claude AI grades every short answer and essay with examiner-level accuracy. MCQs are instant. No marking pile.',
    mockup: <GradingMockup />,
  },
  {
    title: 'Review your gradebook',
    description: "See every student's score at a glance. Colour-coded by performance. Drill into any student to see question-level struggles.",
    mockup: <GradebookMockup />,
  },
]

export default function HowItWorksClient() {
  const [activeTab, setActiveTab] = useState<TabKey>('students')

  return (
    <div className="min-h-screen bg-brand-bg">
      <Navbar />

      {/* Hero */}
      <section className="pt-28 pb-12 md:pt-36 md:pb-16">
        <div className="container-wrapper text-center">
          <motion.h1
            initial={{ opacity: 0, y: 24 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            className="text-3xl sm:text-4xl md:text-5xl font-bold text-brand-text tracking-tight"
          >
            See how ExAIm works
          </motion.h1>
          <motion.p
            initial={{ opacity: 0, y: 24 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.1 }}
            className="mt-4 text-base md:text-lg text-brand-muted max-w-2xl mx-auto"
          >
            Whether you&apos;re a student, teacher, or school — ExAIm fits into your world in minutes.
          </motion.p>
        </div>
      </section>

      {/* Tab switcher */}
      <section className="pb-8 md:pb-12">
        <div className="container-wrapper flex justify-center">
          <motion.div
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.4, delay: 0.2 }}
            className="inline-flex p-1 rounded-full bg-brand-surface border border-brand-border"
          >
            {tabs.map((tab) => (
              <button
                key={tab.key}
                onClick={() => setActiveTab(tab.key)}
                className={`relative px-5 py-2.5 min-h-[44px] text-sm font-medium rounded-full transition-colors duration-200 cursor-pointer ${
                  activeTab === tab.key ? 'text-white' : 'text-brand-muted hover:text-brand-text'
                }`}
              >
                {activeTab === tab.key && (
                  <motion.div
                    layoutId="tab-indicator"
                    className="absolute inset-0 rounded-full bg-indigo-600"
                    transition={{ type: 'spring', bounce: 0.2, duration: 0.5 }}
                  />
                )}
                <span className="relative z-10">{tab.label}</span>
              </button>
            ))}
          </motion.div>
        </div>
      </section>

      {/* Tab content */}
      <section className="section-padding-sm">
        <div className="container-wrapper">
          <AnimatePresence mode="wait">
            {activeTab === 'students' && (
              <motion.div
                key="students"
                initial={{ opacity: 0, y: 16 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -16 }}
                transition={{ duration: 0.3 }}
              >
                <JourneySection steps={studentSteps} />
              </motion.div>
            )}

            {activeTab === 'teachers' && (
              <motion.div
                key="teachers"
                initial={{ opacity: 0, y: 16 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -16 }}
                transition={{ duration: 0.3 }}
              >
                <JourneySection steps={teacherSteps} />
              </motion.div>
            )}

            {activeTab === 'schools' && (
              <motion.div
                key="schools"
                initial={{ opacity: 0, y: 16 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -16 }}
                transition={{ duration: 0.3 }}
              >
                <SchoolJourney />
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </section>

      {/* Bottom CTA */}
      <section className="section-padding">
        <div className="container-wrapper">
          <div className="grid md:grid-cols-2 gap-8 md:gap-12">
            <motion.div
              initial={{ opacity: 0, y: 24 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: '-60px' }}
              transition={{ duration: 0.5 }}
              className="rounded-2xl border border-brand-border bg-brand-surface p-8 text-center"
            >
              <h3 className="text-xl font-bold text-brand-text mb-2">Ready to get started?</h3>
              <p className="text-sm text-brand-muted mb-5">Create your free account in seconds.</p>
              <a
                href="https://app.exaim.com/sign-up"
                className="inline-flex px-6 py-2.5 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white text-sm font-medium transition-colors duration-200"
              >
                Start for free
              </a>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, y: 24 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: '-60px' }}
              transition={{ duration: 0.5, delay: 0.1 }}
              className="rounded-2xl border border-brand-border bg-brand-surface p-8 text-center"
            >
              <h3 className="text-xl font-bold text-brand-text mb-2">Bringing ExAIm to your school?</h3>
              <p className="text-sm text-brand-muted mb-5">Book a demo and we&apos;ll set up a free pilot.</p>
              <Link
                href="/for-schools"
                className="inline-flex px-6 py-2.5 rounded-lg border border-brand-border text-brand-text hover:bg-brand-bg text-sm font-medium transition-colors duration-200"
              >
                Book a demo
              </Link>
            </motion.div>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  )
}
